### ISSUE TITLE
Drupal 9 readiness

### ISSUE THREAD

**Issue by generalredneck** [fourkitchens/sous-drupal-distro#18]
This project doesn't meet all the requirements to be Drupal 9 ready. Specifically it's missing the new `core_version_requirement` key. You can see it in this [change log](https://www.drupal.org/node/3070687)...

Running `drupal-check` on this project yields no errors. so theoretically as soon as all the dependencies are D9 ready, this will be too.
[single-export-sous-2020-09-16T13_52_07+0000.txt](https://github.com/fourkitchens/sous-drupal-distro/files/5232567/single-export-sous-2020-09-16T13_52_07%2B0000.txt)

Here is the report for the exact requirements of Sous and their status. I've updated the Spreadsheet in the "Project level" issue at https://github.com/fourkitchens/sous-drupal-project/issues/8 because it contains these plus the project level requirements which are a few more. If we get these specific projects added to the composer.json with patches/versions that are D9 ready, this is complete.
[upgrade-status-export-2020-09-16T14_21_08+0000.txt](https://github.com/fourkitchens/sous-drupal-distro/files/5232761/upgrade-status-export-2020-09-16T14_21_08%2B0000.txt)

**Comment by ccjjmartin** [comment]
This project is D9 ready, closing.
